import { ArrowUpRight, Heart, MessageSquare, TrendingUp, Users, Radio } from 'lucide-react'
import { citizens, districtNames, fmt, tenge } from '../data/citizens'
import type { Civic } from '../hooks/useCivic'
import { TextLink } from './UI'
export function PulseItem({ icon, count, title, detail, onClick }: { icon: 'fund' | 'petition' | 'issue' | 'vote'; count: string; title: string; detail: string; onClick: () => void }) { const Icon = { fund: Heart, petition: MessageSquare, issue: Users, vote: TrendingUp }[icon]; return <button className="pulse-item" onClick={onClick}><div className={`pulse-icon ${icon}`}><Icon size={17} /></div><div><strong>{count}</strong><p>{title}</p><small>{detail}</small></div><ArrowUpRight size={14} /></button> }
export function CitizenPulse({ civic, navigate }: { civic: Civic; navigate: (page: string) => void }) {
  const school = civic.petitions.find(p => p.id === 'petition-school')!
  const bus = civic.petitions.find(p => p.id === 'petition-bus')!
  const park = civic.projects.find(p => p.id === 'fund-trees')!
  return <section className="card live-pulse"><div className="section-title"><h2>Live City Pulse</h2><span className="live-pill"><i /> DEMO</span></div><p className="small muted">A city is more than its numbers.</p><PulseItem icon="issue" count={`${fmt(citizens.nura.signals)} residents`} title="More schools in Nura" detail={`Trending · ${fmt(school.signatures)} petition signatures`} onClick={() => navigate('petitions')} /><PulseItem icon="vote" count={`${fmt(civic.issues[0].confirmations)} confirmations`} title={civic.issues[0].title} detail={`${districtNames[civic.issues[0].district]} · Citizen report`} onClick={() => navigate('pulse')} /><PulseItem icon="fund" count={`${tenge(park.raised)} funded`} title="Greener streets in Saryarka" detail="Community-powered · Simulated funding" onClick={() => navigate('funding')} /><PulseItem icon="petition" count={`${fmt(bus.signatures)} signatures`} title={bus.title} detail="Collecting support" onClick={() => navigate('petitions')} /><TextLink onClick={() => navigate('pulse')}>Explore all citizen signals</TextLink><div className="pulse-disclaimer">Citizen signals inform decisions. They never change the official score.</div></section>
}
export function LiveActivityTicker({ civic }: { civic: Civic }) { const latest = civic.state.events[0]; return <div className="activity-ticker" aria-live="polite"><Radio size={14} /><strong>ASTANA PULSE</strong><span>{latest ? latest.text : 'Demo feed · Residents are shaping the next chapter of their city.'}</span><small>{latest ? 'Your latest activity' : 'Fictional civic data'}</small></div> }
