"""Generate frontend wire types from Pydantic JSON Schema; use --check in CI."""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from pydantic import BaseModel
from app import schemas


def ts_type(node):
    if "$ref" in node:
        return node["$ref"].rsplit("/", 1)[-1]
    if "enum" in node:
        return " | ".join(json.dumps(value) for value in node["enum"])
    if "anyOf" in node:
        return " | ".join(ts_type(value) for value in node["anyOf"])
    kind = node.get("type")
    if kind == "array":
        return f"Array<{ts_type(node['items'])}>"
    if kind == "object":
        if "properties" not in node:
            key = ts_type(node["propertyNames"]) if "propertyNames" in node else "string"
            return f"Partial<Record<{key}, {ts_type(node['additionalProperties'])}>>"
        required = node.get("required", [])
        fields = [f"  {key}{'' if key in required else '?'}: {ts_type(value)}"
                  for key, value in node["properties"].items()]
        return "{\n" + "\n".join(fields) + "\n}"
    return {"string": "string", "integer": "number", "number": "number",
            "boolean": "boolean", "null": "null"}[kind]


def generate():
    definitions = {}
    for name, model in vars(schemas).items():
        if isinstance(model, type) and issubclass(model, BaseModel) and model.__module__ == schemas.__name__ and name != "Contract":
            definition = model.model_json_schema()
            definitions.update(definition.pop("$defs", {}))
            definitions[name] = definition
    header = "// Generated by backend/scripts/export_types.py. Do not edit manually.\n"
    header += "// UUIDs/datetimes are strings. Money is integer virtual units; validation is server-side.\n\n"
    return header + "\n\n".join(f"export type {name} = {ts_type(schema)}" for name, schema in sorted(definitions.items())) + "\n"


if __name__ == "__main__":
    target = Path(__file__).resolve().parents[2] / "frontend/src/types/domain.ts"
    content = generate()
    if "--check" in sys.argv:
        if not target.exists() or target.read_text(encoding="utf-8") != content:
            raise SystemExit("Frontend contracts are stale. Run python scripts/export_types.py from backend.")
    else:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
