// Generated by backend/scripts/export_types.py. Do not edit manually.
// UUIDs/datetimes are strings. Money is integer virtual units; validation is server-side.

export type AppliedEffect = {
  label: string
  district_id: string
  effects: Partial<Record<Metric, number>>
}

export type CalculationRead = {
  scoring_version: string
  baseline_score: number
  final_score: number
  baseline_critical_count: number
  critical_count: number
  average: number
  weakest: number
  spent_budget: number
  districts: Array<DistrictProjection>
  contributions: Array<AppliedEffect>
}

export type CatalogRead = {
  dataset: DatasetRead
  districts: Array<DistrictRead>
  initiatives: Array<InitiativeRead>
  rules: Array<InitiativeRuleRead>
  baseline: CalculationRead
}

export type CopyRequest = {
  request_id: string
}

export type DatasetCurrentRead = {
  dataset: DatasetRead
  districts: Array<DistrictRead>
  initiatives: Array<InitiativeRead>
  baseline_score: number
}

export type DatasetRead = {
  id: string
  version: string
  name: string
  description: string
  initial_budget: number
  horizon_quarters: number
  scoring_version: string
  metric_weights: Partial<Record<Metric, number>>
  created_at: string
}

export type DecisionRead = {
  id: string
  scenario_id: string
  dataset_id: string
  initiative_id: string
  district_id: string | null
  created_at: string
}

export type DecisionSelect = {
  initiative_id: string
  district_id?: string | null
}

export type DecisionsReplace = {
  decisions: Array<DecisionSelect>
}

export type Direction = "transport" | "ecology" | "social" | "safety" | "services"

export type DistrictPreviewRead = {
  district_id: string
  district_code: string
  district_name: string
  population_share: number
  baseline_score: number
  projected_score: number
  score_delta: number
  baseline_indicators: Indicators
  projected_indicators: Indicators
}

export type DistrictProjection = {
  district_id: string
  name: string
  before: Indicators
  after: Indicators
  baseline_score: number
  final_score: number
}

export type DistrictRead = {
  t1: number
  t2: number
  e1: number
  e2: number
  s1: number
  s2: number
  b1: number
  b2: number
  c1: number
  c2: number
  id: string
  dataset_id: string
  code: string
  name: string
  population_share: number
  created_at: string
}

export type DistrictResultRead = {
  t1: number
  t2: number
  e1: number
  e2: number
  s1: number
  s2: number
  b1: number
  b2: number
  c1: number
  c2: number
  evaluation_id: string
  district_id: string
  dataset_id: string
}

export type EvaluationRead = {
  id: string
  scenario_id: string
  dataset_id: string
  baseline_score: number
  final_score: number
  scoring_version: string
  ai_model: string
  prompt_version: string
  summary: string
  strengths: Array<string>
  risks: Array<string>
  consequences: Array<string>
  recommendations: Array<string>
  created_at: string
  districts: Array<DistrictResultRead>
}

export type ExplanationRead = {
  status: "pending" | "running" | "completed" | "failed"
  payload: ExplanationText | null
  error: string | null
}

export type ExplanationText = {
  summary: string
  strengths: Array<string>
  risks: Array<string>
  consequences: Array<string>
  recommendations: Array<string>
}

export type Impact = {
  t1: number
  t2: number
  e1: number
  e2: number
  s1: number
  s2: number
  b1: number
  b2: number
  c1: number
  c2: number
}

export type Indicators = {
  t1: number
  t2: number
  e1: number
  e2: number
  s1: number
  s2: number
  b1: number
  b2: number
  c1: number
  c2: number
}

export type InitiativeRead = {
  t1: number
  t2: number
  e1: number
  e2: number
  s1: number
  s2: number
  b1: number
  b2: number
  c1: number
  c2: number
  id: string
  dataset_id: string
  code: string
  direction: Direction
  scope: InitiativeScope
  title: string
  cost: number
  lag_quarters: number
  created_at: string
}

export type InitiativeRuleRead = {
  id: string
  dataset_id: string
  first_id: string
  second_id: string
  kind: RuleKind
  scope: RuleScope
  metric: Metric | null
  delta: number | null
  created_at: string
}

export type InitiativeScope = "district" | "city"

export type Metric = "t1" | "t2" | "e1" | "e2" | "s1" | "s2" | "b1" | "b2" | "c1" | "c2"

export type PlanSave = {
  expected_revision: number
  decisions: Array<DecisionSelect>
}

export type RevisionRequest = {
  expected_revision: number
}

export type RuleKind = "synergy" | "conflict"

export type RuleScope = "global" | "same_district" | "first_district"

export type ScenarioCreate = {
  dataset_id: string
  team_name: string
}

export type ScenarioPreviewRead = {
  current_cost: number
  remaining_budget: number
  baseline_score: number
  projected_score: number
  score_delta: number
  districts: Array<DistrictPreviewRead>
}

export type ScenarioRead = {
  id: string
  dataset_id: string
  team_name: string
  status: ScenarioStatus
  created_at: string
  submitted_at: string | null
  initial_budget: number
  spent_budget: number
  remaining_budget: number
  decisions: Array<DecisionRead>
  revision: number
}

export type ScenarioStart = {
  dataset_id: string
  team_name: string
  request_id: string
}

export type ScenarioStatus = "draft" | "submitted" | "evaluated"
