import { test, expect, type Page } from '@playwright/test'

async function enterCitizen(page: Page) {
  await page.goto('/')
  await page.getByRole('button', { name: 'Enter as citizen', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Good afternoon, Astana.' })).toBeVisible()
}
async function navigate(page: Page, label: string) {
  await page.getByRole('navigation', { name: 'Main navigation' }).getByRole('button', { name: label, exact: true }).click()
}

test('citizen actions persist and appear in government signals without changing QoL', async ({ page }) => {
  await enterCitizen(page)
  await navigate(page, 'Petitions')
  const petition = page.locator('.petition-card').filter({ hasText: 'More frequent public transport in Nura' })
  await expect(petition).toContainText('2,486')
  await petition.getByRole('button', { name: 'Sign petition', exact: true }).click()
  await expect(petition).toContainText('2,487')
  await expect(petition.getByRole('button', { name: 'Signed by you' })).toBeDisabled()
  await navigate(page, 'City votes')
  await page.getByRole('button', { name: /Schools & kindergartens/ }).click()
  await page.getByRole('button', { name: 'Cast my vote', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Vote recorded' })).toBeDisabled()
  await expect(page.locator('.voting-card').first()).toContainText('1,483')
  await navigate(page, 'Community funding')
  const project = page.locator('.funding-card').filter({ hasText: 'A playground for every child' })
  await project.getByRole('button', { name: 'Support project' }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByRole('button', { name: '₸5,000', exact: true }).click()
  await dialog.getByRole('button', { name: 'Simulate contribution' }).click()
  await expect(dialog.getByText('Thank you for supporting Astana')).toBeVisible()
  await dialog.getByRole('button', { name: 'Close dialog' }).click()
  await navigate(page, 'Command center')
  await expect(page.getByTestId('score')).toHaveText('52,56')
  await expect(page.locator('.live-pulse')).toContainText('2,487 signatures')
  await page.getByRole('button', { name: 'Listen to the city', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('+₸5,000 demo support')
  await page.keyboard.press('Escape')
  await page.reload()
  await expect(page.getByTestId('score')).toHaveText('52,56')
  await navigate(page, 'Petitions')
  await expect(page.locator('.petition-card').filter({ hasText: 'More frequent public transport in Nura' })).toContainText('2,487')
  await navigate(page, 'City votes')
  await expect(page.getByRole('button', { name: 'Vote recorded' })).toBeDisabled()
  const state = await page.evaluate(() => JSON.parse(localStorage.getItem('astana.civic.v1')!))
  expect(state.donations).toHaveLength(1)
  expect(state.donations[0].amount).toBe(5000)
})

test('citizen points cannot exceed ten and allocation is immutable after submission', async ({ page }) => {
  await enterCitizen(page)
  await navigate(page, 'City votes')
  const add = page.getByRole('button', { name: 'Add point to School in Nura', exact: true })
  await expect(page.getByRole('button', { name: 'Submit priorities' })).toBeDisabled()
  for (let i = 0; i < 10; i++) await add.click()
  await expect(add).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Add point to Park in Saryarka', exact: true })).toBeDisabled()
  await expect(page.getByTestId('citizen-points')).toHaveText('0 / 10 remaining')
  await page.getByRole('button', { name: 'Submit priorities', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Points submitted' })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Remove point from School in Nura', exact: true })).toBeDisabled()
  await page.reload()
  await navigate(page, 'City votes')
  await expect(page.getByRole('button', { name: 'Points submitted' })).toBeDisabled()
})

test('residents can report, confirm, propose and discuss local issues', async ({ page }) => {
  await enterCitizen(page)
  await page.getByRole('button', { name: 'Report a problem', exact: true }).click()
  let dialog = page.getByRole('dialog')
  await dialog.getByLabel('Title', { exact: true }).fill('Accessible sidewalk near the clinic')
  await dialog.getByLabel('Category', { exact: true }).selectOption('safety')
  await dialog.getByLabel('Description', { exact: true }).fill('The crossing needs a ramp for wheelchair users.')
  await dialog.getByLabel('Location', { exact: false }).fill('Nura clinic entrance')
  await dialog.getByRole('button', { name: 'Publish issue' }).click()
  await navigate(page, 'City Pulse')
  const issue = page.locator('.issue-card').filter({ hasText: 'Accessible sidewalk near the clinic' })
  await expect(issue).toContainText('Submitted')
  await issue.getByRole('button', { name: 'I have this problem too' }).click()
  await expect(issue.getByRole('button', { name: 'Confirmed by you' })).toBeDisabled()
  await navigate(page, 'Initiatives')
  await page.getByRole('button', { name: 'Propose an initiative', exact: true }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByLabel('Title', { exact: true }).fill('A library for our neighborhood')
  await dialog.getByLabel('Problem', { exact: true }).fill('Families need a shared reading space.')
  await dialog.getByLabel('Proposed solution', { exact: true }).fill('Convert an unused room into a community library.')
  await dialog.getByLabel('Expected impact', { exact: true }).fill('Accessible learning for everyone.')
  await dialog.getByLabel('Estimated cost (₸)', { exact: true }).fill('2000000')
  await dialog.getByRole('button', { name: 'Publish initiative' }).click()
  await page.locator('.idea-card').filter({ hasText: 'A library for our neighborhood' }).getByRole('button', { name: 'Explore initiative' }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByRole('button', { name: 'Support · 0', exact: true }).click()
  await expect(dialog.getByRole('button', { name: 'Support · 1', exact: true })).toBeDisabled()
  await dialog.getByLabel('Your comment').fill('Include books in Kazakh and Russian.')
  await dialog.getByRole('button', { name: 'Post comment' }).click()
  await expect(dialog).toContainText('Include books in Kazakh and Russian.')
  await page.keyboard.press('Escape')
  await page.reload()
  await navigate(page, 'Initiatives')
  await expect(page.locator('.idea-card').filter({ hasText: 'A library for our neighborhood' })).toContainText('1 supporters')
})

test('petition creation, fictional thresholds, command palette and keyboard district selection', async ({ page }) => {
  await enterCitizen(page)
  await page.getByRole('button', { name: 'Create petition', exact: true }).click()
  let dialog = page.getByRole('dialog')
  await dialog.getByLabel('Title', { exact: true }).fill('More bus shelters in Nura')
  await dialog.getByLabel('Problem', { exact: true }).fill('Residents wait outside in cold weather.')
  await dialog.getByLabel('Proposed solution', { exact: true }).fill('Install enclosed bus shelters.')
  await dialog.getByRole('button', { name: 'Publish petition' }).click()
  await navigate(page, 'Petitions')
  await expect(page.locator('.petition-card').filter({ hasText: 'More bus shelters in Nura' })).toBeVisible()
  await page.keyboard.press('Meta+k')
  dialog = page.getByRole('dialog', { name: 'ASTANA COMMAND' })
  await dialog.getByRole('textbox', { name: 'Search commands' }).fill('Go to Nura')
  await dialog.getByRole('button', { name: 'Go to Nura District intelligence' }).click()
  await expect(page.getByRole('button', { name: 'Explore Nura' })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Explore Yesil' }).focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('button', { name: 'Explore Yesil' })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Simulation settings', exact: true }).click()
  await page.getByLabel('Local district signal').fill('600')
  await page.getByRole('button', { name: 'Save demo milestones' }).click()
  await navigate(page, 'Petitions')
  await expect(page.locator('.thresholds')).toContainText('600')
})

test('desktop, tablet and mobile layouts stay within the viewport', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1050 })
  await page.goto('/')
  await page.screenshot({ path: '/tmp/astana-qa-landing.png', fullPage: true })
  await page.getByRole('button', { name: 'Начать сценарий' }).click()
  await expect(page.getByTestId('score')).toHaveText('52,56')
  await page.screenshot({ path: '/tmp/astana-qa-command.png' })
  for (const width of [1440, 1024, 768, 390]) {
    await page.setViewportSize({ width, height: 1000 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
  }
  await page.setViewportSize({ width: 1440, height: 1050 })
  await navigate(page, 'Community funding')
  await page.screenshot({ path: '/tmp/astana-qa-funding.png' })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
})
