"""initial simulator schema

Revision ID: 0001
Revises: none
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('initial_budget', sa.BigInteger(), nullable=False),
    sa.Column('horizon_quarters', sa.Integer(), nullable=False),
    sa.Column('scoring_version', sa.String(length=64), nullable=False),
    sa.Column('metric_weights', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('horizon_quarters > 0', name=op.f('ck_datasets_positive_horizon')),
    sa.CheckConstraint('initial_budget > 0 AND initial_budget <= 1000000000000', name=op.f('ck_datasets_budget_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets')),
    sa.UniqueConstraint('version', name=op.f('uq_datasets_version'))
    )
    op.create_table('districts',
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('population_share', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('t1', sa.Float(), nullable=False),
    sa.Column('t2', sa.Float(), nullable=False),
    sa.Column('e1', sa.Float(), nullable=False),
    sa.Column('e2', sa.Float(), nullable=False),
    sa.Column('s1', sa.Float(), nullable=False),
    sa.Column('s2', sa.Float(), nullable=False),
    sa.Column('b1', sa.Float(), nullable=False),
    sa.Column('b2', sa.Float(), nullable=False),
    sa.Column('c1', sa.Float(), nullable=False),
    sa.Column('c2', sa.Float(), nullable=False),
    sa.CheckConstraint('b1 >= 0 AND b1 <= 100', name=op.f('ck_districts_b1_range')),
    sa.CheckConstraint('b2 >= 0 AND b2 <= 100', name=op.f('ck_districts_b2_range')),
    sa.CheckConstraint('c1 >= 0 AND c1 <= 100', name=op.f('ck_districts_c1_range')),
    sa.CheckConstraint('c2 >= 0 AND c2 <= 100', name=op.f('ck_districts_c2_range')),
    sa.CheckConstraint('e1 >= 0 AND e1 <= 100', name=op.f('ck_districts_e1_range')),
    sa.CheckConstraint('e2 >= 0 AND e2 <= 100', name=op.f('ck_districts_e2_range')),
    sa.CheckConstraint('population_share > 0 AND population_share <= 1', name=op.f('ck_districts_population_share_range')),
    sa.CheckConstraint('s1 >= 0 AND s1 <= 100', name=op.f('ck_districts_s1_range')),
    sa.CheckConstraint('s2 >= 0 AND s2 <= 100', name=op.f('ck_districts_s2_range')),
    sa.CheckConstraint('t1 >= 0 AND t1 <= 100', name=op.f('ck_districts_t1_range')),
    sa.CheckConstraint('t2 >= 0 AND t2 <= 100', name=op.f('ck_districts_t2_range')),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_districts_dataset_id_datasets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_districts')),
    sa.UniqueConstraint('dataset_id', 'code', name=op.f('uq_districts_dataset_id')),
    sa.UniqueConstraint('id', 'dataset_id', name=op.f('uq_districts_id'))
    )
    op.create_index(op.f('ix_districts_dataset_id'), 'districts', ['dataset_id'], unique=False)
    op.create_table('initiatives',
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.Enum('transport', 'ecology', 'social', 'safety', 'services', name='direction', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('scope', sa.Enum('district', 'city', name='initiative_scope', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('cost', sa.BigInteger(), nullable=False),
    sa.Column('lag_quarters', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('t1', sa.Float(), nullable=False),
    sa.Column('t2', sa.Float(), nullable=False),
    sa.Column('e1', sa.Float(), nullable=False),
    sa.Column('e2', sa.Float(), nullable=False),
    sa.Column('s1', sa.Float(), nullable=False),
    sa.Column('s2', sa.Float(), nullable=False),
    sa.Column('b1', sa.Float(), nullable=False),
    sa.Column('b2', sa.Float(), nullable=False),
    sa.Column('c1', sa.Float(), nullable=False),
    sa.Column('c2', sa.Float(), nullable=False),
    sa.CheckConstraint('b1 >= -100 AND b1 <= 100', name=op.f('ck_initiatives_b1_range')),
    sa.CheckConstraint('b2 >= -100 AND b2 <= 100', name=op.f('ck_initiatives_b2_range')),
    sa.CheckConstraint('c1 >= -100 AND c1 <= 100', name=op.f('ck_initiatives_c1_range')),
    sa.CheckConstraint('c2 >= -100 AND c2 <= 100', name=op.f('ck_initiatives_c2_range')),
    sa.CheckConstraint('cost >= 0 AND cost <= 1000000000000', name=op.f('ck_initiatives_cost_range')),
    sa.CheckConstraint('e1 >= -100 AND e1 <= 100', name=op.f('ck_initiatives_e1_range')),
    sa.CheckConstraint('e2 >= -100 AND e2 <= 100', name=op.f('ck_initiatives_e2_range')),
    sa.CheckConstraint('lag_quarters >= 0', name=op.f('ck_initiatives_nonnegative_lag')),
    sa.CheckConstraint('s1 >= -100 AND s1 <= 100', name=op.f('ck_initiatives_s1_range')),
    sa.CheckConstraint('s2 >= -100 AND s2 <= 100', name=op.f('ck_initiatives_s2_range')),
    sa.CheckConstraint('t1 >= -100 AND t1 <= 100', name=op.f('ck_initiatives_t1_range')),
    sa.CheckConstraint('t2 >= -100 AND t2 <= 100', name=op.f('ck_initiatives_t2_range')),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_initiatives_dataset_id_datasets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_initiatives')),
    sa.UniqueConstraint('dataset_id', 'code', name=op.f('uq_initiatives_dataset_id')),
    sa.UniqueConstraint('id', 'dataset_id', name=op.f('uq_initiatives_id'))
    )
    op.create_index(op.f('ix_initiatives_dataset_id'), 'initiatives', ['dataset_id'], unique=False)
    op.create_table('scenarios',
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('team_name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'evaluated', name='scenario_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("(status = 'draft' AND submitted_at IS NULL) OR (status IN ('submitted', 'evaluated') AND submitted_at IS NOT NULL)", name=op.f('ck_scenarios_submission_state')),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_scenarios_dataset_id_datasets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenarios')),
    sa.UniqueConstraint('id', 'dataset_id', name=op.f('uq_scenarios_id'))
    )
    op.create_index(op.f('ix_scenarios_dataset_id'), 'scenarios', ['dataset_id'], unique=False)
    op.create_table('decisions',
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('initiative_id', sa.Uuid(), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['district_id', 'dataset_id'], ['districts.id', 'districts.dataset_id'], name=op.f('fk_decisions_district_id_districts')),
    sa.ForeignKeyConstraint(['initiative_id', 'dataset_id'], ['initiatives.id', 'initiatives.dataset_id'], name=op.f('fk_decisions_initiative_id_initiatives')),
    sa.ForeignKeyConstraint(['scenario_id', 'dataset_id'], ['scenarios.id', 'scenarios.dataset_id'], name=op.f('fk_decisions_scenario_id_scenarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions')),
    sa.UniqueConstraint('scenario_id', 'initiative_id', name=op.f('uq_decisions_scenario_id'))
    )
    op.create_index(op.f('ix_decisions_initiative_id'), 'decisions', ['initiative_id'], unique=False)
    op.create_index(op.f('ix_decisions_scenario_id'), 'decisions', ['scenario_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('baseline_score', sa.Float(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('scoring_version', sa.String(length=64), nullable=False),
    sa.Column('ai_model', sa.String(length=200), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('risks', sa.JSON(), nullable=False),
    sa.Column('consequences', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('baseline_score <= 100 AND baseline_score >= -1.7976931348623157e308', name=op.f('ck_evaluations_baseline_range')),
    sa.CheckConstraint('final_score <= 100 AND final_score >= -1.7976931348623157e308', name=op.f('ck_evaluations_final_range')),
    sa.ForeignKeyConstraint(['scenario_id', 'dataset_id'], ['scenarios.id', 'scenarios.dataset_id'], name=op.f('fk_evaluations_scenario_id_scenarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluations')),
    sa.UniqueConstraint('id', 'dataset_id', name=op.f('uq_evaluations_id')),
    sa.UniqueConstraint('scenario_id', name=op.f('uq_evaluations_scenario_id'))
    )
    op.create_table('initiative_rules',
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('first_id', sa.Uuid(), nullable=False),
    sa.Column('second_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('synergy', 'conflict', name='rule_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('scope', sa.Enum('global', 'same_district', 'first_district', name='rule_scope', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('metric', sa.Enum('t1', 't2', 'e1', 'e2', 's1', 's2', 'b1', 'b2', 'c1', 'c2', name='rule_metric', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("(kind = 'synergy' AND scope = 'first_district' AND metric IS NOT NULL AND delta IS NOT NULL AND delta >= -100 AND delta <= 100) OR (kind = 'conflict' AND scope IN ('global', 'same_district') AND metric IS NULL AND delta IS NULL)", name=op.f('ck_initiative_rules_rule_shape')),
    sa.CheckConstraint('first_id <> second_id', name=op.f('ck_initiative_rules_different_initiatives')),
    sa.ForeignKeyConstraint(['first_id', 'dataset_id'], ['initiatives.id', 'initiatives.dataset_id'], name=op.f('fk_initiative_rules_first_id_initiatives')),
    sa.ForeignKeyConstraint(['second_id', 'dataset_id'], ['initiatives.id', 'initiatives.dataset_id'], name=op.f('fk_initiative_rules_second_id_initiatives')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_initiative_rules')),
    sa.UniqueConstraint('first_id', 'second_id', 'kind', name=op.f('uq_initiative_rules_first_id'))
    )
    op.create_table('district_results',
    sa.Column('evaluation_id', sa.Uuid(), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('t1', sa.Float(), nullable=False),
    sa.Column('t2', sa.Float(), nullable=False),
    sa.Column('e1', sa.Float(), nullable=False),
    sa.Column('e2', sa.Float(), nullable=False),
    sa.Column('s1', sa.Float(), nullable=False),
    sa.Column('s2', sa.Float(), nullable=False),
    sa.Column('b1', sa.Float(), nullable=False),
    sa.Column('b2', sa.Float(), nullable=False),
    sa.Column('c1', sa.Float(), nullable=False),
    sa.Column('c2', sa.Float(), nullable=False),
    sa.CheckConstraint('b1 >= 0 AND b1 <= 100', name=op.f('ck_district_results_b1_range')),
    sa.CheckConstraint('b2 >= 0 AND b2 <= 100', name=op.f('ck_district_results_b2_range')),
    sa.CheckConstraint('c1 >= 0 AND c1 <= 100', name=op.f('ck_district_results_c1_range')),
    sa.CheckConstraint('c2 >= 0 AND c2 <= 100', name=op.f('ck_district_results_c2_range')),
    sa.CheckConstraint('e1 >= 0 AND e1 <= 100', name=op.f('ck_district_results_e1_range')),
    sa.CheckConstraint('e2 >= 0 AND e2 <= 100', name=op.f('ck_district_results_e2_range')),
    sa.CheckConstraint('s1 >= 0 AND s1 <= 100', name=op.f('ck_district_results_s1_range')),
    sa.CheckConstraint('s2 >= 0 AND s2 <= 100', name=op.f('ck_district_results_s2_range')),
    sa.CheckConstraint('t1 >= 0 AND t1 <= 100', name=op.f('ck_district_results_t1_range')),
    sa.CheckConstraint('t2 >= 0 AND t2 <= 100', name=op.f('ck_district_results_t2_range')),
    sa.ForeignKeyConstraint(['district_id', 'dataset_id'], ['districts.id', 'districts.dataset_id'], name=op.f('fk_district_results_district_id_districts')),
    sa.ForeignKeyConstraint(['evaluation_id', 'dataset_id'], ['evaluations.id', 'evaluations.dataset_id'], name=op.f('fk_district_results_evaluation_id_evaluations')),
    sa.PrimaryKeyConstraint('evaluation_id', 'district_id', name=op.f('pk_district_results'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('district_results')
    op.drop_table('initiative_rules')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_decisions_scenario_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_initiative_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_scenarios_dataset_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_initiatives_dataset_id'), table_name='initiatives')
    op.drop_table('initiatives')
    op.drop_index(op.f('ix_districts_dataset_id'), table_name='districts')
    op.drop_table('districts')
    op.drop_table('datasets')
    # ### end Alembic commands ###
