"""scenario sessions and durable analysis

Revision ID: 0002
Revises: 0001
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculations',
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_calculations_scenario_id_scenarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calculations')),
    sa.UniqueConstraint('scenario_id', name=op.f('uq_calculations_scenario_id'))
    )
    op.create_table('explanations',
    sa.Column('calculation_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed')", name=op.f('ck_explanations_status_values')),
    sa.ForeignKeyConstraint(['calculation_id'], ['calculations.id'], name=op.f('fk_explanations_calculation_id_calculations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_explanations')),
    sa.UniqueConstraint('calculation_id', name=op.f('uq_explanations_calculation_id'))
    )
    op.add_column('scenarios', sa.Column('owner_hash', sa.String(length=64), nullable=True))
    op.add_column('scenarios', sa.Column('request_id', sa.Uuid(), nullable=True))
    op.add_column('scenarios', sa.Column('revision', sa.Integer(), server_default='0', nullable=False))
    op.create_index(op.f('ix_scenarios_owner_hash'), 'scenarios', ['owner_hash'], unique=False)
    op.create_index('uq_scenarios_owner_request', 'scenarios', ['owner_hash', 'request_id'], unique=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_scenarios_owner_request', table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_owner_hash'), table_name='scenarios')
    op.drop_column('scenarios', 'revision')
    op.drop_column('scenarios', 'request_id')
    op.drop_column('scenarios', 'owner_hash')
    op.drop_table('explanations')
    op.drop_table('calculations')
    # ### end Alembic commands ###
